(() => {
  "use strict";
  const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n||0));
  let sb,current="users",cache={};
  const msg=(s,ok=false)=>{const e=$("#admin-message");e.textContent=s||"";e.className=`app-message ${ok?"success":"error"}`};
  async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw error;return data;}
  async function boot(){sb=await window.ShowLinkSupabase.load();const {data:{session}}=await sb.auth.getSession();if(!session){location.replace('/login.html?next=/admin.html');return;}try{const admin=await rpc('is_current_user_admin');if(!admin){document.body.innerHTML='<main style="max-width:620px;margin:15vh auto;padding:30px;text-align:center;font-family:Inter,sans-serif"><h1>Akses Ditolak</h1><p>Akun ini bukan administrator.</p><a href="/dashboard.html">Kembali ke Dashboard</a></main>';return;}await Promise.all([loadStats(),loadGateway(),loadTab('users'),loadWithdrawNotifications()]);}catch(e){msg(e.message||'Gagal memuat Admin Panel');}}
  async function loadStats(){const d=await rpc('admin_dashboard_stats');$("#s-users").textContent=d.users;$("#s-links").textContent=d.payment_links;$("#s-orders").textContent=d.orders;$("#s-gross").textContent=money(d.gross_sales);$("#s-platform").textContent=money(d.platform_earnings);$("#s-pending").textContent=money(d.pending_settlement);}
  async function loadGateway(){const g=await rpc('admin_get_gateway_settings');$("#cashi-enabled").checked=!!g.cashi_enabled;$("#bayargg-enabled").checked=!!g.bayargg_enabled;$("#default-gateway").value=g.default_gateway;$("#platform-fee").value=g.platform_fee_percent;$("#settlement-days").value=g.settlement_days;}
  async function loadWithdrawNotifications(){const rows=await rpc('admin_withdrawal_notifications',{p_limit:10});const el=$("#withdraw-notifications");if(!el)return;if(!rows?.length){el.innerHTML='<div class="app-empty">Belum ada notifikasi withdrawal.</div>';return;}el.innerHTML=rows.map(n=>`<div class="admin-notice-item ${n.is_read?'':'unread'}"><strong>${esc(n.title)}</strong><span>${esc(n.message)}</span><small>${new Date(n.created_at).toLocaleString('id-ID')}</small></div>`).join('');}
  async function loadTab(tab){current=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const map={users:['admin_users',['ID','Username','Email','Plan','Admin','Saldo']],links:['admin_payment_links',['Title','Owner','Harga','Status','Sales','Views']],orders:['admin_orders',['Order','Seller','Amount','Status','Provider','Waktu']],withdrawals:['admin_withdrawals',['User','Amount','Fee','Total Debit','Status','Method','Waktu']]};const [fn,heads]=map[tab];$("#admin-head").innerHTML='<tr>'+heads.map(h=>`<th>${h}</th>`).join('')+'</tr>';const data=await rpc(fn,{p_limit:100});cache[tab]=data||[];render(tab);if(tab==='withdrawals')await loadWithdrawNotifications();}
  function render(tab){const rows=cache[tab]||[];if(!rows.length){$("#admin-body").innerHTML='<tr><td colspan="8" class="app-empty">Tidak ada data.</td></tr>';return;}let html='';if(tab==='users')html=rows.map(r=>`<tr><td>${r.id.slice(0,8)}…</td><td>${esc(r.username)}</td><td>${esc(r.auth_email||'-')}</td><td>${esc(r.plan)}</td><td>${r.is_admin?'YES':'-'}</td><td>${money(r.balance)}</td></tr>`).join('');if(tab==='links')html=rows.map(r=>`<tr><td>${esc(r.title)}<small><br>/${esc(r.slug)}</small></td><td>${esc(r.owner_username||'-')}</td><td>${money(r.price)}</td><td><span class="status-pill">${esc(r.status)}</span></td><td>${r.sales_count}</td><td>${r.views}</td></tr>`).join('');if(tab==='orders')html=rows.map(r=>`<tr><td>${esc(r.order_number)}</td><td>${esc(r.seller_username||'-')}</td><td>${money(r.amount)}</td><td><span class="status-pill">${esc(r.status)}</span></td><td>${esc(r.provider||'-')}</td><td>${new Date(r.created_at).toLocaleString('id-ID')}</td></tr>`).join('');if(tab==='withdrawals')html=rows.map(r=>{const total=Number(r.amount||0)+Number(r.fee||0);return `<tr><td>${esc(r.username)}</td><td>${money(r.amount)}</td><td>${money(r.fee)}</td><td>${money(total)}</td><td><span class="status-pill">${esc(r.status)}</span></td><td>${esc(r.method_type||'-')}<br><small>${esc(r.account_name||'')} • ${esc(r.account_number||'')}</small></td><td>${new Date(r.created_at).toLocaleString('id-ID')}<br><div class="admin-actions">${r.status==='pending'?`<button data-withdraw="${r.id}" data-status="paid">Approve</button><button data-withdraw="${r.id}" data-status="rejected">Reject</button>`:''}${r.status==='processing'?`<button data-withdraw="${r.id}" data-status="paid">Approve</button><button data-withdraw="${r.id}" data-status="rejected">Reject</button>`:''}</div>${r.status==='rejected'&&r.admin_note?`<small>Alasan: ${esc(r.admin_note)}</small>`:''}</td></tr>`}).join('');$("#admin-body").innerHTML=html;}
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  $("#gateway-form").addEventListener('submit',async e=>{e.preventDefault();try{await rpc('admin_update_gateway_settings',{p_cashi_enabled:$("#cashi-enabled").checked,p_bayargg_enabled:$("#bayargg-enabled").checked,p_default_gateway:$("#default-gateway").value,p_platform_fee_percent:Number($("#platform-fee").value),p_settlement_days:Number($("#settlement-days").value)});msg('Pengaturan gateway berhasil disimpan.',true);}catch(e){msg(e.message||'Gagal menyimpan gateway');}});
  document.addEventListener('click',async e=>{const tab=e.target.closest('[data-tab]');if(tab){try{await loadTab(tab.dataset.tab)}catch(x){msg(x.message)}}const w=e.target.closest('[data-withdraw]');if(w){let note='';if(w.dataset.status==='rejected'){note=prompt('Alasan penolakan withdrawal:')||'';if(!note.trim())return;}try{await rpc('admin_update_withdrawal',{p_withdrawal_id:w.dataset.withdraw,p_status:w.dataset.status,p_admin_note:note});await loadTab('withdrawals');await loadStats();await loadWithdrawNotifications();msg(w.dataset.status==='paid'?'Withdrawal berhasil di-approve.':'Withdrawal berhasil ditolak dan alasan dikirim ke user.',true);window.ShowLinkNavbar?.refreshNotifications()}catch(x){msg(x.message||'Gagal memperbarui withdrawal')}}});
  boot();
})();
