(() => {
  "use strict";
  const $=s=>document.querySelector(s);
  const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n||0));
  let sb,current="users",cache={};
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const msg=(s,ok=false)=>{const e=$("#admin-message");e.textContent=s||"";e.className=`app-message ${ok?"success":"error"}`;e.hidden=!s;};
  async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw error;return data;}
  async function userAction(action,user_id){const {data,error}=await sb.functions.invoke("admin-user-action",{body:{action,user_id}});if(error)throw error;if(data?.error)throw new Error(data.error);return data;}
  async function boot(){
    try{sb=await window.ShowLinkSupabase.load();const {data:{session}}=await sb.auth.getSession();if(!session){location.replace('/login.html?next=/admin.html');return;}
      const admin=await rpc('is_current_user_admin');if(!admin){document.body.innerHTML='<main style="max-width:620px;margin:15vh auto;padding:30px;text-align:center;font-family:Inter,sans-serif"><h1>Akses Ditolak</h1><p>Akun ini bukan administrator.</p><a href="/dashboard.html">Kembali ke Dashboard</a></main>';return;}
      await Promise.all([loadStats(),loadGateway(),loadControls(),loadTab('users')]);
    }catch(e){msg(e.message||'Gagal memuat Admin Panel');}
  }
  async function loadStats(){const d=await rpc('admin_dashboard_stats');$("#s-users").textContent=d.users;$("#s-links").textContent=d.payment_links;$("#s-orders").textContent=d.orders;$("#s-gross").textContent=money(d.gross_sales);$("#s-platform").textContent=money(d.platform_earnings);$("#s-pending").textContent=money(d.pending_settlement);}
  async function loadGateway(){const g=await rpc('admin_get_gateway_settings');$("#cashi-enabled").checked=!!g.cashi_enabled;$("#bayargg-enabled").checked=!!g.bayargg_enabled;$("#default-gateway").value=g.default_gateway;$("#platform-fee").value=g.platform_fee_percent;$("#settlement-days").value=g.settlement_days;}
  async function loadControls(){const c=await rpc('admin_get_platform_controls');const open=!!c.withdrawals_open;$("#withdrawals-open").checked=open;$("#withdraw-control-title").textContent=open?'Withdrawal TERBUKA':'Withdrawal DITUTUP';$("#withdraw-control-desc").textContent=open?'User dapat mengajukan withdrawal.':'Pengajuan baru diblokir di backend. Withdrawal yang sudah masuk tetap bisa diproses.';}
  const maps={users:{fn:'admin_users',heads:['ID','Username','Email','Plan','Admin','Saldo','Status','Aksi']},links:{fn:'admin_payment_links',heads:['File / Payment Link','Pemilik','Harga','Status','Sales','Views','Aksi']},orders:{fn:'admin_orders',heads:['Order','Seller','Amount','Status','Provider','Waktu']},withdrawals:{fn:'admin_withdrawals',heads:['User','Amount','Net','Status','Metode','Waktu / Aksi']}};
  async function loadTab(tab){current=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$("#admin-table-caption").textContent=({users:'Kelola akun: ban, buka ban, atau hapus user.',links:'Edit metadata dan status atau hapus payment link.',orders:'Pantau semua order platform.',withdrawals:'Approve, proses, atau reject permintaan withdrawal.'})[tab];const spec=maps[tab];$("#admin-head").innerHTML='<tr>'+spec.heads.map(h=>`<th>${h}</th>`).join('')+'</tr>';$("#admin-body").innerHTML='<tr><td colspan="8">Memuat data…</td></tr>';const data=await rpc(spec.fn,{p_limit:200});cache[tab]=Array.isArray(data)?data:[];render(tab);}
  function actionBtn(label,attrs,klass=''){return `<button type="button" class="admin-table-action ${klass}" ${attrs}>${label}</button>`;}
  function render(tab){const rows=cache[tab]||[];if(!rows.length){$("#admin-body").innerHTML='<tr><td colspan="8" class="app-empty">Tidak ada data.</td></tr>';return;}let html='';
    if(tab==='users')html=rows.map(r=>`<tr><td><small>${esc(String(r.id).slice(0,8))}…</small></td><td><strong>${esc(r.username)}</strong>${r.is_admin?'<small><br>Administrator</small>':''}</td><td>${esc(r.auth_email||'-')}</td><td>${esc(r.plan||'free')}</td><td>${r.is_admin?'YES':'-'}</td><td>${money(r.balance)}</td><td><span class="status-pill ${r.is_banned?'status-banned':'status-active'}">${r.is_banned?'BANNED':'Aktif'}</span></td><td><div class="admin-actions">${r.is_admin?'<span>Protected</span>':`${actionBtn(r.is_banned?'Buka ban':'Ban',`data-user-action="${r.is_banned?'unban_user':'ban_user'}" data-user-id="${esc(r.id)}"`,r.is_banned?'positive':'danger')}${actionBtn('Hapus',`data-user-action="delete_user" data-user-id="${esc(r.id)}"`,'danger')}`}</div></td></tr>`).join('');
    if(tab==='links')html=rows.map(r=>`<tr><td><strong>${esc(r.title)}</strong><small><br>/${esc(r.slug)}</small></td><td>${esc(r.owner_username||'-')}</td><td>${money(r.price)}</td><td><span class="status-pill">${esc(r.status)}</span></td><td>${Number(r.sales_count||0)}</td><td>${Number(r.views||0)}</td><td><div class="admin-actions">${actionBtn('Edit',`data-link-edit="${esc(r.id)}"`)}${actionBtn('Hapus',`data-link-delete="${esc(r.id)}"`,'danger')}</div></td></tr>`).join('');
    if(tab==='orders')html=rows.map(r=>`<tr><td>${esc(r.order_number)}</td><td>${esc(r.seller_username||'-')}</td><td>${money(r.amount)}</td><td><span class="status-pill">${esc(r.status)}</span></td><td>${esc(r.provider||'-')}</td><td>${r.created_at?new Date(r.created_at).toLocaleString('id-ID'):'-'}</td></tr>`).join('');
    if(tab==='withdrawals')html=rows.map(r=>`<tr><td><strong>${esc(r.username)}</strong><small><br>${esc(String(r.user_id||'').slice(0,8))}</small></td><td>${money(r.amount)}<small><br>Fee ${money(r.fee)}</small></td><td>${money(r.net_amount)}</td><td><span class="status-pill ${r.status==='paid'?'status-active':r.status==='rejected'?'status-banned':''}">${esc(r.status)}</span>${r.admin_note?`<small><br>${esc(r.admin_note)}</small>`:''}</td><td>${esc(r.method_type||'-')}<br><small>${esc(r.account_name||'')} · ${esc(r.account_number||'')}</small></td><td>${r.created_at?new Date(r.created_at).toLocaleString('id-ID'):'-'}<div class="admin-actions">${['pending','processing'].includes(r.status)?`${actionBtn('Approve / Paid',`data-withdraw="${esc(r.id)}" data-status="paid"`,'positive')}${actionBtn('Proses',`data-withdraw="${esc(r.id)}" data-status="processing"`)}${actionBtn('Reject',`data-withdraw="${esc(r.id)}" data-status="rejected"`,'danger')}`:''}</div></td></tr>`).join('');
    $("#admin-body").innerHTML=html;
  }
  async function updateWithdrawal(id,status){let note='';if(status==='rejected'){note=prompt('Catatan penolakan (akan diberitahukan ke user):');if(note===null)return;note=note.trim();if(!note)note='Permintaan tidak dapat disetujui.';}await rpc('admin_update_withdrawal',{p_withdrawal_id:id,p_status:status,p_admin_note:note||null});}
  $("#gateway-form").addEventListener('submit',async e=>{e.preventDefault();try{await rpc('admin_update_gateway_settings',{p_cashi_enabled:$("#cashi-enabled").checked,p_bayargg_enabled:$("#bayargg-enabled").checked,p_default_gateway:$("#default-gateway").value,p_platform_fee_percent:Number($("#platform-fee").value),p_settlement_days:Number($("#settlement-days").value)});msg('Pengaturan gateway berhasil disimpan.',true);}catch(e){msg(e.message||'Gagal menyimpan gateway');}});
  $("#announcement-form").addEventListener('submit',async e=>{e.preventDefault();const title=$("#announcement-title").value.trim(),message=$("#announcement-message").value.trim(),link=$("#announcement-link").value.trim()||'/dashboard.html';if(!confirm(`Kirim pengumuman “${title}” ke SELURUH user?`))return;const button=e.submitter;button.disabled=true;try{const r=await rpc('admin_announce_all',{p_title:title,p_message:message,p_link_url:link});$("#announcement-form").reset();$("#announcement-link").value='/dashboard.html';msg(`Pengumuman berhasil dikirim ke ${r.recipients} akun.`,true);}catch(x){msg(x.message||'Gagal mengirim pengumuman');}finally{button.disabled=false;}});
  $("#withdrawals-open").addEventListener('change',async e=>{const next=e.target.checked;if(!confirm(next?'Buka pengajuan withdrawal untuk semua user?':'Tutup pengajuan withdrawal untuk semua user?')){e.target.checked=!next;return;}e.target.disabled=true;try{await rpc('admin_set_withdrawals_open',{p_open:next});await loadControls();msg(next?'Pengajuan withdrawal dibuka.':'Pengajuan withdrawal ditutup.',true);}catch(x){e.target.checked=!next;msg(x.message||'Gagal mengubah status withdrawal');}finally{e.target.disabled=false;}});
  document.addEventListener('click',async e=>{
    const tab=e.target.closest('[data-tab]');if(tab){try{await loadTab(tab.dataset.tab);msg('');}catch(x){msg(x.message||'Gagal memuat data');}return;}
    if(e.target.closest('#refresh-admin')){try{await Promise.all([loadStats(),loadControls(),loadTab(current)]);msg('Data admin diperbarui.',true);}catch(x){msg(x.message||'Refresh gagal');}return;}
    if(e.target.closest('#reload-current-tab')){try{await loadTab(current);msg('Data dimuat ulang.',true);}catch(x){msg(x.message||'Gagal memuat data');}return;}
    const ua=e.target.closest('[data-user-action]');if(ua){const action=ua.dataset.userAction,id=ua.dataset.userId;const promptText=action==='delete_user'?'HAPUS PERMANEN user ini? Akun tidak dapat dipulihkan.':action==='ban_user'?'Ban user ini agar tidak bisa login?':'Buka ban user ini?';if(!confirm(promptText))return;ua.disabled=true;try{await userAction(action,id);await loadTab('users');await loadStats();msg(action==='delete_user'?'User berhasil dihapus.':action==='ban_user'?'User berhasil dibanned.':'Ban user berhasil dibuka.',true);}catch(x){msg(x.message||'Aksi user gagal');ua.disabled=false;}return;}
    const le=e.target.closest('[data-link-edit]');if(le){const row=(cache.links||[]).find(x=>x.id===le.dataset.linkEdit);if(!row)return;const title=prompt('Judul file/payment link:',row.title);if(title===null)return;const priceRaw=prompt('Harga (angka, minimal Rp100):',String(row.price));if(priceRaw===null)return;const price=Number(priceRaw);const status=prompt('Status: draft, active, paused, expired, deleted',row.status);if(status===null)return;try{await rpc('admin_update_payment_link',{p_link_id:row.id,p_title:title,p_price:price,p_status:status.trim().toLowerCase(),p_description:null});await loadTab('links');await loadStats();msg('Payment link berhasil diperbarui.',true);}catch(x){msg(x.message||'Gagal mengedit payment link');}return;}
    const ld=e.target.closest('[data-link-delete]');if(ld){const row=(cache.links||[]).find(x=>x.id===ld.dataset.linkDelete);if(!row||!confirm(`Hapus/nonaktifkan “${row.title}”? Link akan ditandai deleted dan tidak dihapus fisik dari database.`))return;try{await rpc('admin_delete_payment_link',{p_link_id:row.id});await loadTab('links');await loadStats();msg('Payment link ditandai deleted.',true);}catch(x){msg(x.message||'Gagal menghapus payment link');}return;}
    const w=e.target.closest('[data-withdraw]');if(w){const status=w.dataset.status;const label=status==='paid'?'Approve dan tandai sudah dibayar':status==='rejected'?'Reject dan kembalikan saldo user':'Pindahkan ke status processing';if(!confirm(`${label}? User akan menerima notifikasi.`))return;w.disabled=true;try{const changed=await updateWithdrawal(w.dataset.withdraw,status);if(!changed)return;await loadTab('withdrawals');await loadStats();msg('Status withdrawal diperbarui dan notifikasi dibuat.',true);}catch(x){msg(x.message||'Gagal memperbarui withdrawal');w.disabled=false;}return;}
    const bulkApprove=e.target.closest('#bulk-withdraw-approve');const bulkReject=e.target.closest('#bulk-withdraw-reject');if(bulkApprove||bulkReject){const pending=(cache.withdrawals||[]).filter(r=>['pending','processing'].includes(r.status));if(!pending.length){msg('Tidak ada withdrawal pending untuk diproses.',true);return;}const status=bulkApprove?'paid':'rejected';if(!confirm(`${status==='paid'?'Approve / Paid':'Reject'} ${pending.length} withdrawal yang pending/processing? Setiap user akan menerima notifikasi.${status==='rejected'?' Saldo dikembalikan.':''}`))return;let bulkNote='';if(status==='rejected'){bulkNote=prompt('Catatan penolakan untuk semua withdrawal terpilih:');if(bulkNote===null)return;bulkNote=bulkNote.trim()||'Permintaan tidak dapat disetujui.';}const b=bulkApprove||bulkReject;b.disabled=true;let ok=0,failed=0;try{for(const r of pending){try{await updateWithdrawal(r.id,status,bulkNote);ok++;}catch{failed++;}}await loadTab('withdrawals');await loadStats();msg(`Bulk selesai: ${ok} berhasil${failed?`, ${failed} gagal`:''}.`,failed===0);}catch(x){msg(x.message||'Bulk action gagal');}finally{b.disabled=false;}return;}
  });
  boot();
})();
