(() => {
"use strict";
const $=(s,r=document)=>r.querySelector(s);
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sb=null, session=null, rows=[];
const body=()=>$('#payment-links-body');
function toast(msg,type='success'){
 let el=$('#sl-manage-toast'); if(!el){el=document.createElement('div');el.id='sl-manage-toast';document.body.appendChild(el)}
 el.className='sl-manage-toast '+type; el.innerHTML=`<i class="fa-solid ${type==='error'?'fa-circle-exclamation':'fa-circle-check'}"></i><span>${esc(msg)}</span>`; clearTimeout(el._t); el.classList.add('show'); el._t=setTimeout(()=>el.classList.remove('show'),2200);
}
function render(){
 if(!rows.length){body().innerHTML='<tr><td colspan="6" class="empty-state"><div class="sl-empty-icon"><i class="fa-solid fa-link-slash"></i></div><strong>Belum ada Payment Link</strong><span>Buat Payment Link pertama kamu dan mulai menerima pembayaran.</span><a class="btn btn-primary" href="/payment-link.html"><i class="fa-solid fa-plus"></i> Buat sekarang</a></td></tr>';return;}
 body().innerHTML=rows.map(x=>{
 const url=`https://showlink.my.id/p/${encodeURIComponent(x.slug)}`;
 return `<tr data-row-id="${esc(x.id)}"><td><div class="sl-link-cell"><div class="sl-link-icon"><i class="fa-solid fa-link"></i></div><div><strong>${esc(x.title||'Tanpa judul')}</strong><span class="sub">/p/${esc(x.slug)}</span></div></div></td><td><strong>${money(x.price)}</strong></td><td>${Number(x.views||0).toLocaleString('id-ID')}</td><td>${Number(x.sales_count||0).toLocaleString('id-ID')}</td><td><span class="status-chip ${esc(x.status||'active')}"><i class="fa-solid fa-circle"></i>${esc(x.status||'active')}</span></td><td><div class="row-actions"><a class="mini open" href="/p/${encodeURIComponent(x.slug)}" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square"></i> Buka</a><button class="mini" data-edit-id="${esc(x.id)}"><i class="fa-solid fa-pen"></i> Edit</button><button class="mini" data-copy="${esc(url)}"><i class="fa-regular fa-copy"></i> Salin</button><button class="mini danger" data-delete-id="${esc(x.id)}"><i class="fa-solid fa-trash-can"></i> Hapus</button></div></td></tr>`;
 }).join('');
 body().querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.innerHTML='<i class="fa-solid fa-check"></i> Tersalin';b.classList.add('copied');setTimeout(()=>{b.innerHTML='<i class="fa-regular fa-copy"></i> Salin';b.classList.remove('copied')},1500)}catch(_){prompt('Salin URL:',b.dataset.copy)}});
 body().querySelectorAll('[data-edit-id]').forEach(b=>b.onclick=()=>openEditor(rows.find(x=>String(x.id)===String(b.dataset.editId))));
 body().querySelectorAll('[data-delete-id]').forEach(b=>b.onclick=()=>removeLink(rows.find(x=>String(x.id)===String(b.dataset.deleteId)),b));
}
function ensureModal(){
 if($('#sl-edit-modal'))return;
 document.body.insertAdjacentHTML('beforeend',`<div class="sl-modal" id="sl-edit-modal" aria-hidden="true"><div class="sl-modal-backdrop" data-close-edit></div><section class="sl-modal-card" role="dialog" aria-modal="true" aria-labelledby="sl-edit-title"><button class="sl-modal-close" type="button" data-close-edit aria-label="Tutup"><i class="fa-solid fa-xmark"></i></button><div class="sl-modal-head"><span class="sl-modal-kicker"><i class="fa-solid fa-pen"></i> EDIT PAYMENT LINK</span><h2 id="sl-edit-title">Edit Payment Link</h2><p>Perbarui judul, deskripsi, konten, harga, atau status link kamu.</p></div><form id="sl-edit-form"><input type="hidden" name="id"><label><span class="sl-field-label">Judul</span><input name="title" maxlength="120" required></label><label><span class="sl-field-label">Deskripsi</span><textarea name="description" rows="3" maxlength="500"></textarea></label><label><span class="sl-field-label">Konten</span><textarea name="content_text" rows="7" required></textarea></label><div class="sl-edit-grid"><label><span class="sl-field-label">Harga (Rp)</span><input name="price" type="number" min="2000" max="100000" step="1000" required></label><label><span class="sl-field-label">Status</span><select name="status"><option value="active">Aktif</option><option value="paused">Dijeda</option><option value="draft">Draft</option></select></label></div><div class="sl-edit-actions"><button type="button" class="btn secondary" data-close-edit>Batal</button><button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Simpan perubahan</button></div></form></section></div>`);
 document.querySelectorAll('[data-close-edit]').forEach(x=>x.addEventListener('click',closeEditor));
 $('#sl-edit-form').addEventListener('submit',saveEdit);
}
function openEditor(x){if(!x)return;ensureModal();const f=$('#sl-edit-form');f.elements.id.value=x.id;f.elements.title.value=x.title||'';f.elements.description.value=x.description||'';f.elements.content_text.value=x.content_text||x.content_html?.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'')||'';f.elements.price.value=Number(x.price)||2000;f.elements.status.value=x.status||'active';$('#sl-edit-modal').classList.add('is-open');$('#sl-edit-modal').setAttribute('aria-hidden','false');document.body.classList.add('sl-modal-open');setTimeout(()=>f.elements.title.focus(),80)}
function closeEditor(){const m=$('#sl-edit-modal');if(!m)return;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('sl-modal-open')}
function contentHtml(text){return esc(text).replace(/((?:https?:\/\/|www\.)[^\s<]+)/gi,m=>`<a href="${esc(/^www\./i.test(m)?'https://'+m:m)}" target="_blank" rel="noopener noreferrer">${m}</a>`).replace(/\r?\n/g,'<br>')}
async function saveEdit(e){e.preventDefault();const f=e.currentTarget;const b=f.querySelector('button[type=submit]');const original=b.innerHTML;const price=Number(f.elements.price.value);if(!Number.isFinite(price)||price<2000||price>100000){toast('Harga harus Rp2.000–Rp100.000.','error');return}b.disabled=true;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Menyimpan...';try{const id=f.elements.id.value;const payload={title:f.elements.title.value.trim(),description:f.elements.description.value.trim()||null,content_text:f.elements.content_text.value.trim(),content_html:contentHtml(f.elements.content_text.value.trim()),price,status:f.elements.status.value,updated_at:new Date().toISOString()};if(!payload.title||!payload.content_text)throw new Error('Judul dan konten wajib diisi.');const {data,error}=await sb.from('payment_links').update(payload).eq('id',id).eq('owner_id',session.user.id).select('id,slug,title,description,price,status,views,sales_count,created_at,updated_at,content_text,content_html').single();if(error)throw error;const i=rows.findIndex(x=>String(x.id)===String(id));if(i>=0)rows[i]={...rows[i],...data};closeEditor();render();toast('Payment Link berhasil diperbarui.')}catch(err){console.error(err);toast(err?.message||'Gagal menyimpan perubahan.','error')}finally{b.disabled=false;b.innerHTML=original}}
async function removeLink(x,b){if(!x)return;const ok=confirm(`Hapus Payment Link “${x.title||x.slug}”?\n\nTindakan ini tidak bisa dibatalkan.`);if(!ok)return;b.disabled=true;const old=b.innerHTML;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i>';try{const {error}=await sb.from('payment_links').delete().eq('id',x.id).eq('owner_id',session.user.id);if(error)throw error;rows=rows.filter(r=>String(r.id)!==String(x.id));render();toast('Payment Link berhasil dihapus.')}catch(err){console.error(err);toast(err?.message||'Gagal menghapus Payment Link.','error');b.disabled=false;b.innerHTML=old}}
async function init(){
 sb=await window.ShowLinkSupabase.load();const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session)return location.replace('/login.html?redirect='+encodeURIComponent(location.pathname));
 const {data,error}=await sb.from('payment_links').select('id,slug,title,description,content_text,content_html,price,status,views,sales_count,created_at,updated_at').eq('owner_id',session.user.id).order('created_at',{ascending:false});
 if(error)throw error;rows=data||[];render();
}
document.addEventListener('DOMContentLoaded',()=>init().catch(e=>{console.error(e);const b=body();if(b)b.innerHTML=`<tr><td colspan="6" class="empty-state"><div class="sl-empty-icon"><i class="fa-solid fa-triangle-exclamation"></i></div><strong>Gagal memuat Payment Link</strong><span>${esc(e.message||'Silakan coba lagi.')}</span></td></tr>`}));
})();
