(() => {
"use strict";
const $=(s,r=document)=>r.querySelector(s);
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sb=null, session=null, rows=[];
const body=()=>$('#payment-links-body');
const lang=()=>window.ShowLinkLanguage?.getLanguage?.()||localStorage.getItem('showlink-language')||'id';
const T={
 id:{title:'Payment Link Saya',intro:'Kelola semua Payment Link yang kamu buat.',create:'Buat Payment Link',createSub:'Mulai buat link pembayaran baru',link:'Payment Link',price:'Harga',views:'Views',sales:'Terjual',status:'Status',actions:'Aksi',open:'Buka',edit:'Edit',copy:'Salin',copied:'Tersalin',delete:'Hapus',empty:'Belum ada Payment Link',emptySub:'Buat Payment Link pertama kamu dan mulai menerima pembayaran.',createNow:'Buat sekarang',active:'Aktif',paused:'Dijeda',draft:'Draft',expired:'Kedaluwarsa',editKicker:'EDIT PAYMENT LINK',editTitle:'Edit Payment Link',editSub:'Perbarui judul, deskripsi, konten, harga, atau status link kamu.',titleField:'Judul',description:'Deskripsi',content:'Konten',priceField:'Harga (Rp)',statusField:'Status',cancel:'Batal',save:'Simpan perubahan',saving:'Menyimpan...',close:'Tutup',saved:'Payment Link berhasil diperbarui.',deleted:'Payment Link berhasil dihapus.',deleteConfirm:'Hapus Payment Link “{name}”?\n\nTindakan ini tidak bisa dibatalkan.',required:'Judul dan konten wajib diisi.',priceError:'Harga harus Rp2.000–Rp100.000.',copyPrompt:'Salin URL:',loadError:'Gagal memuat Payment Link'},
 en:{title:'My Payment Links',intro:'Manage all Payment Links you create.',create:'Create Payment Link',createSub:'Start a new payment link',link:'Payment Link',price:'Price',views:'Views',sales:'Sales',status:'Status',actions:'Actions',open:'Open',edit:'Edit',copy:'Copy',copied:'Copied',delete:'Delete',empty:'No Payment Links yet',emptySub:'Create your first Payment Link and start accepting payments.',createNow:'Create now',active:'Active',paused:'Paused',draft:'Draft',expired:'Expired',editKicker:'EDIT PAYMENT LINK',editTitle:'Edit Payment Link',editSub:'Update the title, description, content, price, or link status.',titleField:'Title',description:'Description',content:'Content',priceField:'Price (IDR)',statusField:'Status',cancel:'Cancel',save:'Save changes',saving:'Saving...',close:'Close',saved:'Payment Link updated successfully.',deleted:'Payment Link deleted successfully.',deleteConfirm:'Delete Payment Link “{name}”?\n\nThis action cannot be undone.',required:'Title and content are required.',priceError:'Price must be between Rp2,000 and Rp100,000.',copyPrompt:'Copy URL:',loadError:'Failed to load Payment Links'}
};
const t=k=>T[lang()][k]||T.id[k]||k;
function applyStaticLanguage(){
 const set=(id,key)=>{const e=$('#'+id);if(e)e.textContent=t(key)};
 set('manage-title','title');set('manage-intro','intro');set('create-link-label','create');set('create-link-sub','createSub');
 set('th-link','link');set('th-price','price');set('th-views','views');set('th-sales','sales');set('th-status','status');set('th-actions','actions');
 const a=document.querySelector('.sl-create-btn');if(a)a.setAttribute('aria-label',t('create'));
}
function toast(msg,type='success'){
 let el=$('#sl-manage-toast'); if(!el){el=document.createElement('div');el.id='sl-manage-toast';document.body.appendChild(el)}
 el.className='sl-manage-toast '+type; el.innerHTML=`<i class="fa-solid ${type==='error'?'fa-circle-exclamation':'fa-circle-check'}"></i><span>${esc(msg)}</span>`; clearTimeout(el._t); el.classList.add('show'); el._t=setTimeout(()=>el.classList.remove('show'),2200);
}
function statusLabel(status){const s=String(status||'active').toLowerCase();return t(s==='active'?'active':s==='paused'?'paused':s==='draft'?'draft':s==='expired'?'expired':'active')}
function render(){
 applyStaticLanguage();
 if(!rows.length){body().innerHTML=`<tr><td colspan="6" class="empty-state"><div class="sl-empty-icon"><i class="fa-solid fa-link-slash"></i></div><strong>${esc(t('empty'))}</strong><span>${esc(t('emptySub'))}</span><a class="btn btn-primary" href="/payment-link.html"><i class="fa-solid fa-plus"></i> ${esc(t('createNow'))}</a></td></tr>`;return;}
 body().innerHTML=rows.map(x=>{
 const url=`https://showlink.my.id/p/${encodeURIComponent(x.slug)}`;
 return `<tr data-row-id="${esc(x.id)}"><td><div class="sl-link-cell"><div class="sl-link-icon"><i class="fa-solid fa-link"></i></div><div><strong>${esc(x.title||'Untitled')}</strong><span class="sub">/p/${esc(x.slug)}</span></div></div></td><td><strong>${money(x.price)}</strong></td><td>${Number(x.views||0).toLocaleString(lang()==='en'?'en-US':'id-ID')}</td><td>${Number(x.sales_count||0).toLocaleString(lang()==='en'?'en-US':'id-ID')}</td><td><span class="status-chip ${esc(x.status||'active')}"><i class="fa-solid fa-circle"></i>${esc(statusLabel(x.status))}</span></td><td><div class="row-actions"><a class="mini open" href="/p/${encodeURIComponent(x.slug)}" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square"></i> ${esc(t('open'))}</a><button class="mini" data-edit-id="${esc(x.id)}"><i class="fa-solid fa-pen"></i> ${esc(t('edit'))}</button><button class="mini" data-copy="${esc(url)}"><i class="fa-regular fa-copy"></i> ${esc(t('copy'))}</button><button class="mini danger" data-delete-id="${esc(x.id)}"><i class="fa-solid fa-trash-can"></i> ${esc(t('delete'))}</button></div></td></tr>`;
 }).join('');
 body().querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.innerHTML=`<i class="fa-solid fa-check"></i> ${esc(t('copied'))}`;b.classList.add('copied');setTimeout(()=>{b.innerHTML=`<i class="fa-regular fa-copy"></i> ${esc(t('copy'))}`;b.classList.remove('copied')},1500)}catch(_){prompt(t('copyPrompt'),b.dataset.copy)}});
 body().querySelectorAll('[data-edit-id]').forEach(b=>b.onclick=()=>openEditor(rows.find(x=>String(x.id)===String(b.dataset.editId))));
 body().querySelectorAll('[data-delete-id]').forEach(b=>b.onclick=()=>removeLink(rows.find(x=>String(x.id)===String(b.dataset.deleteId)),b));
}
function ensureModal(){
 if($('#sl-edit-modal')){translateModal();return}
 document.body.insertAdjacentHTML('beforeend',`<div class="sl-modal" id="sl-edit-modal" aria-hidden="true"><div class="sl-modal-backdrop" data-close-edit></div><section class="sl-modal-card" role="dialog" aria-modal="true" aria-labelledby="sl-edit-title"><button class="sl-modal-close" type="button" data-close-edit aria-label="${esc(t('close'))}"><i class="fa-solid fa-xmark"></i></button><div class="sl-modal-head"><span class="sl-modal-kicker"><i class="fa-solid fa-pen"></i> <span id="edit-kicker">${esc(t('editKicker'))}</span></span><h2 id="sl-edit-title">${esc(t('editTitle'))}</h2><p id="edit-sub">${esc(t('editSub'))}</p></div><form id="sl-edit-form"><input type="hidden" name="id"><label><span>${esc(t('titleField'))}</span><input name="title" maxlength="120" required></label><label><span>${esc(t('description'))}</span><textarea name="description" rows="3" maxlength="500"></textarea></label><label><span>${esc(t('content'))}</span><textarea name="content_text" rows="7" required></textarea></label><div class="sl-edit-grid"><label><span>${esc(t('priceField'))}</span><input name="price" type="number" min="2000" max="100000" step="1000" required></label><label><span>${esc(t('statusField'))}</span><select name="status"><option value="active">${esc(t('active'))}</option><option value="paused">${esc(t('paused'))}</option><option value="draft">${esc(t('draft'))}</option></select></label></div><div class="sl-edit-actions"><button type="button" class="btn secondary" data-close-edit>${esc(t('cancel'))}</button><button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> <span class="edit-save-label">${esc(t('save'))}</span></button></div></form></section></div>`);
 document.querySelectorAll('[data-close-edit]').forEach(x=>x.addEventListener('click',closeEditor));
 $('#sl-edit-form').addEventListener('submit',saveEdit);
}
function translateModal(){
 const m=$('#sl-edit-modal');if(!m)return;
 const q=(s)=>$(s,m);
 const map=[['#edit-kicker','editKicker'],['#sl-edit-title','editTitle'],['#edit-sub','editSub']];map.forEach(([s,k])=>{const e=q(s);if(e)e.textContent=t(k)});
 const labels=m.querySelectorAll('#sl-edit-form > label, .sl-edit-grid label');const keys=['titleField','description','content','priceField','statusField'];labels.forEach((l,i)=>{const sp=l.querySelector('span');if(sp&&keys[i])sp.textContent=t(keys[i])});
 const close=m.querySelectorAll('[data-close-edit]');close.forEach((e,i)=>{if(i===0)e.setAttribute('aria-label',t('close'));if(i>0)e.textContent=t('cancel')});
 const save=m.querySelector('.edit-save-label');if(save)save.textContent=t('save');
 const opts=m.querySelectorAll('select[name="status"] option');if(opts.length>=3){opts[0].textContent=t('active');opts[1].textContent=t('paused');opts[2].textContent=t('draft')}
}
function openEditor(x){if(!x)return;ensureModal();const f=$('#sl-edit-form');f.elements.id.value=x.id;f.elements.title.value=x.title||'';f.elements.description.value=x.description||'';f.elements.content_text.value=x.content_text||x.content_html?.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'')||'';f.elements.price.value=Number(x.price)||2000;f.elements.status.value=x.status||'active';$('#sl-edit-modal').classList.add('is-open');$('#sl-edit-modal').setAttribute('aria-hidden','false');document.body.classList.add('sl-modal-open');setTimeout(()=>f.elements.title.focus(),80)}
function closeEditor(){const m=$('#sl-edit-modal');if(!m)return;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('sl-modal-open')}
function contentHtml(text){return esc(text).replace(/((?:https?:\/\/|www\.)[^\s<]+)/gi,m=>`<a href="${esc(/^www\./i.test(m)?'https://'+m:m)}" target="_blank" rel="noopener noreferrer">${m}</a>`).replace(/\r?\n/g,'<br>')}
async function saveEdit(e){e.preventDefault();const f=e.currentTarget;const b=f.querySelector('button[type=submit]');const original=b.innerHTML;const price=Number(f.elements.price.value);if(!Number.isFinite(price)||price<2000||price>100000){toast(t('priceError'),'error');return}b.disabled=true;b.innerHTML=`<i class="fa-solid fa-spinner fa-spin"></i> <span>${esc(t('saving'))}</span>`;try{const id=f.elements.id.value;const payload={title:f.elements.title.value.trim(),description:f.elements.description.value.trim()||null,content_text:f.elements.content_text.value.trim(),content_html:contentHtml(f.elements.content_text.value.trim()),price,status:f.elements.status.value,updated_at:new Date().toISOString()};if(!payload.title||!payload.content_text)throw new Error(t('required'));const {data,error}=await sb.from('payment_links').update(payload).eq('id',id).eq('owner_id',session.user.id).select('id,slug,title,description,price,status,views,sales_count,created_at,updated_at,content_text,content_html').single();if(error)throw error;const i=rows.findIndex(x=>String(x.id)===String(id));if(i>=0)rows[i]={...rows[i],...data};closeEditor();render();toast(t('saved'))}catch(err){console.error(err);toast(err?.message||t('loadError'),'error')}finally{b.disabled=false;b.innerHTML=original}}
async function removeLink(x,b){if(!x)return;const ok=confirm(t('deleteConfirm').replace('{name}',x.title||x.slug));if(!ok)return;b.disabled=true;const old=b.innerHTML;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i>';try{const {error}=await sb.from('payment_links').delete().eq('id',x.id).eq('owner_id',session.user.id);if(error)throw error;rows=rows.filter(r=>String(r.id)!==String(x.id));render();toast(t('deleted'))}catch(err){console.error(err);toast(err?.message||t('loadError'),'error');b.disabled=false;b.innerHTML=old}}
async function init(){
 sb=await window.ShowLinkSupabase.load();const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session)return location.replace('/login.html?redirect='+encodeURIComponent(location.pathname));
 const {data,error}=await sb.from('payment_links').select('id,slug,title,description,content_text,content_html,price,status,views,sales_count,created_at,updated_at').eq('owner_id',session.user.id).order('created_at',{ascending:false});
 if(error)throw error;rows=data||[];render();
 window.addEventListener('showlink:language-change',()=>{render();translateModal()});
}
document.addEventListener('DOMContentLoaded',()=>init().catch(e=>{console.error(e);const b=body();if(b)b.innerHTML=`<tr><td colspan="6" class="empty-state"><div class="sl-empty-icon"><i class="fa-solid fa-triangle-exclamation"></i></div><strong>${esc(t('loadError'))}</strong><span>${esc(e.message||'Please try again.')}</span></td></tr>`}));
})();
