/* ShowLink — shared imported navbar */
(() => {
  "use strict";
  const C={home:"/",dashboard:"/dashboard.html",paymentLink:"/payment-link.html",orders:"/order.html",notifications:"/notifikasi.html",withdraw:"/withdraw.html",myLinks:"/kelola-tautan.html",profile:"/profil.html",settings:"/pengaturan.html",about:"/about.html",admin:"/admin.html",login:"/login.html",register:"/register.html"};
  let authUser=null, loaded=false;
  const stored=()=>{try{return JSON.parse(localStorage.getItem("showlink_user")||"null")}catch{return null}};
  const logged=()=>!!authUser||!!stored();
  const t=k=>window.ShowLinkLanguage?.t?.(k)||({orders:"Order",withdraw:"Withdraw",myPaymentLinks:"My Payment Link",profile:"Profil",settings:"Pengaturan",about:"About",notifications:"Notifikasi",paymentLink:"Payment Link",dashboard:"Dashboard",signOut:"Logout",home:"Home",login:"Login",register:"Register"}[k]||k);
  const icon=(cls,name)=>`<i class="fa-solid ${name}${cls?` ${cls}`:""}" aria-hidden="true"></i>`;
  const link=(href,ic,key)=>`<a class="sl-nav-link" href="${href}" data-nav-link><span>${icon(ic.cls,ic.name)}</span><span data-i18n="${key}">${t(key)}</span></a>`;
  function authMarkup(){return `${link(C.dashboard,{cls:"sl-icon-blue",name:"fa-gauge-high"},"dashboard")}${link(C.paymentLink,{cls:"sl-icon-yellow",name:"fa-credit-card"},"paymentLink")}${link(C.orders,{cls:"sl-icon-purple",name:"fa-receipt"},"orders")}${link(C.notifications,{cls:"sl-icon-pink",name:"fa-bell"},"notifications")}${link(C.withdraw,{cls:"sl-icon-green",name:"fa-money-bill-transfer"},"withdraw")}${link(C.myLinks,{cls:"sl-icon-blue",name:"fa-link"},"myPaymentLinks")}<div class="sl-drawer-divider"></div>${link(C.profile,{cls:"sl-icon-purple",name:"fa-user"},"profile")}${link(C.settings,{cls:"sl-icon-yellow",name:"fa-gear"},"settings")}${link(C.about,{cls:"sl-icon-blue",name:"fa-circle-info"},"about")}<a class="sl-nav-link sl-admin-nav" href="${C.admin}" data-admin-nav hidden>${icon("sl-icon-red","fa-shield-halved")}<span>Admin Panel</span></a><div class="sl-drawer-divider"></div><a class="sl-nav-link sl-nav-logout" href="#logout" data-logout>${icon("sl-icon-red","fa-right-from-bracket")}<span data-i18n="signOut">${t("signOut")}</span></a>`;}
  function guestMarkup(){return `${link(C.home,{cls:"sl-icon-blue",name:"fa-house"},"home")}<div class="sl-drawer-divider"></div>${link(C.login,{cls:"sl-icon-green",name:"fa-right-to-bracket"},"login")}${link(C.register,{cls:"sl-icon-yellow",name:"fa-user-plus"},"register")}`;}
  async function loadTemplate(){if(loaded)return true;const host=document.querySelector("[data-showlink-navbar]");if(!host)return false;try{const r=await fetch("/components/navbar.html",{cache:"no-store"});if(!r.ok)throw new Error(`navbar.html ${r.status}`);host.innerHTML=await r.text();loaded=true;return true}catch(e){console.error("ShowLink navbar import failed:",e);host.innerHTML="";return false;}}
  function closeDrawer(){const h=document.querySelector("[data-showlink-navbar]");if(!h)return;h.querySelector("[data-showlink-drawer]")?.classList.remove("is-open");h.querySelector("[data-showlink-overlay]")?.classList.remove("is-open");h.querySelector("[data-showlink-menu]")?.setAttribute("aria-expanded","false");document.documentElement.classList.remove("sl-drawer-open");}
  function openDrawer(){const h=document.querySelector("[data-showlink-navbar]");if(!h)return;h.querySelector("[data-showlink-drawer]")?.classList.add("is-open");h.querySelector("[data-showlink-overlay]")?.classList.add("is-open");h.querySelector("[data-showlink-menu]")?.setAttribute("aria-expanded","true");document.documentElement.classList.add("sl-drawer-open");}
  async function refreshAdminVisibility(){const els=document.querySelectorAll("[data-admin-nav]");if(!els.length||!logged())return;try{const sb=await window.ShowLinkSupabase?.load?.();if(!sb)return;const {data:{session}}=await sb.auth.getSession();if(!session)return;const {data,error}=await sb.rpc("is_current_user_admin");if(!error&&data===true)els.forEach(e=>e.hidden=false);}catch{}}
  async function refreshNotificationBadge(){const h=document.querySelector("[data-showlink-navbar]"),b=h?.querySelector("[data-notification-badge]");if(!b)return;b.hidden=true;b.textContent="";h?.querySelector("[data-navbar-notification]")?.classList.remove("has-notifications");if(!logged())return;try{const sb=await window.ShowLinkSupabase?.load?.();if(!sb)return;const {data:{session}}=await sb.auth.getSession();const uid=session?.user?.id;if(!uid)return;const {count,error}=await sb.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",uid).eq("is_read",false);if(error||!count)return;b.textContent=count>99?"99+":String(count);b.hidden=false;h?.querySelector("[data-navbar-notification]")?.classList.add("has-notifications");}catch{}}
  async function render(){const host=document.querySelector("[data-showlink-navbar]");if(!host)return;if(!(await loadTemplate()))return;const is=logged();const menu=host.querySelector("[data-navbar-menu]"),actions=host.querySelector("[data-navbar-auth-actions]"),notice=host.querySelector("[data-navbar-notification]");if(menu)menu.innerHTML=is?authMarkup():guestMarkup();if(notice){notice.href=is?C.notifications:C.login;notice.setAttribute("aria-label",t("notifications"));notice.title=t("notifications");}if(actions){actions.innerHTML=is?"":`<a class="sl-btn sl-btn-ghost sl-desktop-action" href="${C.login}">${icon("sl-icon-green","fa-right-to-bracket")}<span>${t("login")}</span></a><a class="sl-btn sl-btn-primary sl-desktop-action" href="${C.register}">${icon("","fa-user-plus")}<span>${t("register")}</span></a>`;}
    host.querySelector("[data-showlink-menu]")?.addEventListener("click",()=>host.querySelector("[data-showlink-drawer]")?.classList.contains("is-open")?closeDrawer():openDrawer());host.querySelector("[data-showlink-close]")?.addEventListener("click",closeDrawer);host.querySelector("[data-showlink-overlay]")?.addEventListener("click",closeDrawer);host.querySelectorAll("[data-nav-link]").forEach(a=>a.addEventListener("click",closeDrawer));
    document.body.classList.add("showlink-navbar-page");window.dispatchEvent(new CustomEvent("showlink:navbar-rendered"));refreshNotificationBadge();refreshAdminVisibility();
  }
  function logoutReady(){if(window.__showLinkLogoutReady)return;window.__showLinkLogoutReady=true;document.addEventListener("click",async e=>{const b=e.target instanceof Element?e.target.closest("[data-logout]"):null;if(!b)return;e.preventDefault();closeDrawer();try{const sb=await window.ShowLinkSupabase?.load?.();await sb?.auth.signOut();}catch{}localStorage.removeItem("showlink_user");window.dispatchEvent(new CustomEvent("showlink:auth-change",{detail:{user:null}}));location.replace(C.home);});}
  window.ShowLinkNavbar={render,refresh:()=>{authUser=stored();loaded=false;render()},refreshNotifications:refreshNotificationBadge,setAuth:u=>{authUser=u||null;loaded=false;render()}};
  window.addEventListener("showlink:auth-change",e=>{authUser=e.detail?.user||null;loaded=false;render();});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer();});logoutReady();
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{authUser=stored();render()},{once:true});else{authUser=stored();render();}
})();
